version : "3"
services:
  sequeries-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sequeries-api
    depends_on:
      - sequeries-pg
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "1230:80"
      - "1231:1231"
    environment:
      APP_NAME: 'Sequeries'
      APP_DEBUG: 'true'
      APP_URL: 'http://221.230.1.1'
      DB_CONNECTION: 'pgsql'
      QUEUE_CONNECTION: 'database'
      XDEBUG_CONFIG: "mode=debug,coverage,develop client_host=host.docker.internal discover_client_host=1 start_with_request=yes"
      GITHUB_USERNAME: 'jdecode'
      GITHUB_REPONAME: 'sequeries'
      GITHUB_CALLBACK: '/auth/github/callback'
      GITHUB_CLIENT_ID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      GITHUB_CLIENT_SECRET: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    networks:
      sequeries-api-network:
        ipv4_address: 221.230.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  sequeries-pg:
    image: postgres:latest
    ports:
        - "1232:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: test_db
    container_name: sequeries-pg
    volumes:
      - sequeries-pg-disk:/var/lib/postgres
    networks:
      sequeries-api-network:
        ipv4_address: 221.230.1.2

  sequeries-tf:
      build:
        context: .
        dockerfile: terraform/Dockerfile
      container_name: sequeries-tf
      volumes:
          - .:/var/www/html
      environment:
        HEROKU_API_KEY: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
        AWS_ACCESS_KEY_ID: 'xxxxxxxxxxxxxxxxxxxx'
        AWS_SECRET_ACCESS_KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        POSTMAN_API_KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        CIRCLECI_API_KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

      networks:
        sequeries-api-network:
          ipv4_address: 221.230.1.3

# On-disk storage of DB data, when containers are stopped
volumes:
  sequeries-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  sequeries-api-network:
    ipam:
      driver: default
      config:
        - subnet: 221.230.0.0/16
